[package]
name = "looper"
version = "0.0.1"
authors = ["Rustcod Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/looper"
repository = "https://github.com/rustcod/looper"
description = """
A fixed step loop
"""

[dependencies]
